### ISSUE TITLE
Adding new widgets to Dimension shouldn't be hard

### ISSUE THREAD

**Issue by turt2live** [turt2live/matrix-dimension#124]
Currently it seems to require updating half the web UI just to register the thing

**Comment by MTRNord** [comment]
Not sure if it is worth a new issue or fits here, but dev docs on it might be useful too.

**Comment by turt2live** [comment]
I've reduced the touch points down to just a few:
* Add your widget yaml
* Add your avatar image
* Create your configuration component
* In `web/app/shared/integration.service.ts` add your integration to the giant map

Keeping this open until developer docs exist.

**Comment by MTRNord** [comment]
Not sure if this the correct issue to notice this but I am still unsure if it would be advisable to add licenses of the avatar images to the repo. Currently they are added without either a mention where they are from or what their license it. (It might make problems as soon as someone wants to use it in a comercial way I guess)

**Comment by turt2live** [comment]
Good point. Currently they all should be licensed for commercial re-distribution, but I'll double check and update any which may not be.

**Comment by turt2live** [comment]
Developer documentation added here: https://github.com/turt2live/matrix-dimension/blob/master/docs/development/adding_widgets.md

If it's unclear, please let me know.

**Comment by dontub** [comment]
Meanwhile https://github.com/turt2live/matrix-dimension/blob/master/docs/development/adding_widgets.md was removed. Is there any replacement?
