### ISSUE TITLE
EmptyError: no elements in sequence when trying to host my own server

### ISSUE THREAD

**Issue by saket424** [turt2live/matrix-dimension#129]
I tried to host matrix-dimension service of my own using the instructions in the README.md behind an nginx proxy

The server starts correctly
export NODE_ENV=production
node app.js
Dec-6-2017 15:59:15.412 +00:00 info [UpstreamConfiguration] Loaded upstream 'vector' as: {"name":"vector","url":"https://scalar.vector.im/api"}
Unable to load crypto module: crypto will be disabled: Error: global.Olm is not defined
Dec-6-2017 15:59:15.850 +00:00 info [Integrations] Discovering integrations
Dec-6-2017 15:59:15.879 +00:00 info [Integrations] Discovered 11 integrations. Parsing definitions...
Dec-6-2017 15:59:15.880 +00:00 info [Integrations] Preparing custom_widget.yaml
Dec-6-2017 15:59:15.882 +00:00 info [Integrations] Preparing giphy.yaml
Dec-6-2017 15:59:15.883 +00:00 info [Integrations] Preparing google.yaml
Dec-6-2017 15:59:15.884 +00:00 info [Integrations] Preparing guggy.yaml
Dec-6-2017 15:59:15.886 +00:00 info [Integrations] Preparing imgur.yaml
Dec-6-2017 15:59:15.887 +00:00 info [Integrations] Preparing irc_bridge.yaml
Dec-6-2017 15:59:15.888 +00:00 info [Integrations] Preparing rssbot.yaml
Dec-6-2017 15:59:15.888 +00:00 info [Integrations] Preparing travisci.yaml
Dec-6-2017 15:59:15.889 +00:00 info [Integrations] Preparing twitch_widget.yaml
Dec-6-2017 15:59:15.889 +00:00 info [Integrations] Preparing wikipedia.yaml
Dec-6-2017 15:59:15.890 +00:00 info [Integrations] Preparing youtube_widget.yaml
Dec-6-2017 15:59:15.891 +00:00 info [Integrations] Loaded 11 integrations
Dec-6-2017 15:59:15.975 +00:00 info [app] Bootstrapping Dimension...
Dec-6-2017 15:59:15.976 +00:00 info [DimensionStore] Running migrations
[INFO] No migrations to run
[INFO] Done
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:236:13
Dec-6-2017 15:59:16.926 +00:00 info [IRCApi] Setting up IRC API
Dec-6-2017 15:59:16.929 +00:00 info [Dimension] API and UI listening on 0.0.0.0:8184
Dec-6-2017 15:59:16.929 +00:00 info [app] Demo bot enabled - starting up
Dec-6-2017 15:59:16.931 +00:00 info [DemoBot] Constructing bot as @dimension:i1.setlurs.com
Dec-6-2017 15:59:16.934 +00:00 info [DemoBot] Starting bot

I then switched the config.json to point to mine instead of yours. BTW, your works well and mine does not
{
    "default_hs_url": "https://i1.example.com",
    "default_is_url": "",
    "brand": "Riot",
"integrations_ui_url": "https://i1.example.com/riot",
"integrations_rest_url": "https://i1.example.com/api/v1/scalar",
"integrations_widgets_urls": ["https://i1.example.com/widgets"],
"xintegrations_ui_url": "https://dimension.t2bot.io/riot",
"xintegrations_rest_url": "https://dimension.t2bot.io/api/v1/scalar",
"xintegrations_widgets_urls": ["https://dimension.t2bot.io/widgets"],
    "bug_report_endpoint_url": "",
    "features": {
        "feature_groups": "labs",
        "feature_pinning": "labs"
    },
    "default_federate": true,
    "roomDirectory": {
        "servers": [
            "a2.example.com",
            "matrix.org"
        ]
    },
    "welcomeUserId": "@riot-bot:matrix.org",
    "piwik": {
        "url": "https://piwik.riot.im/",
        "siteId": 1
    }

I get the following error in my console logs and I see no widgets, I just cloned your repository and did not modify anything. just want to establish a baseline that I can host my own dimension server first before getting dangerous with it. Any ideas of what I may have configured wrong ??

Starting load of AsyncWrapper for modal
rageshake.js:65 AsyncWrapper load completed with IntegrationsManager
core.es5.js:1020 ERROR Error: Uncaught (in promise): EmptyError: no elements in sequence
EmptyError: no elements in sequence
    at new EmptyError (EmptyError.js:27)
    at FirstSubscriber._complete (first.js:154)
    at FirstSubscriber.Subscriber.complete (Subscriber.js:121)
    at MergeMapSubscriber._complete (mergeMap.js:144)
    at MergeMapSubscriber.Subscriber.complete (Subscriber.js:121)
    at MapSubscriber.Subscriber._complete (Subscriber.js:139)
    at MapSubscriber.Subscriber.complete (Subscriber.js:121)
    at EmptyObservable._subscribe (EmptyObservable.js:82)
    at EmptyObservable.Observable._trySubscribe (Observable.js:173)
    at EmptyObservable.Observable.subscribe (Observable.js:161)
    at new EmptyError (EmptyError.js:27)
    at FirstSubscriber._complete (first.js:154)
    at FirstSubscriber.Subscriber.complete (Subscriber.js:121)
    at MergeMapSubscriber._complete (mergeMap.js:144)
    at MergeMapSubscriber.Subscriber.complete (Subscriber.js:121)
    at MapSubscriber.Subscriber._complete (Subscriber.js:139)
    at MapSubscriber.Subscriber.complete (Subscriber.js:121)
    at EmptyObservable._subscribe (EmptyObservable.js:82)
    at EmptyObservable.Observable._trySubscribe (Observable.js:173)
    at EmptyObservable.Observable.subscribe (Observable.js:161)
    at resolvePromise (zone.js:824)
    at resolvePromise (zone.js:795)
    at zone.js:873
    at ZoneDelegate.invokeTask (zone.js:425)
    at Object.onInvokeTask (core.es5.js:3881)
    at ZoneDelegate.invokeTask (zone.js:424)
    at Zone.runTask (zone.js:192)
    at drainMicroTaskQueue (zone.js:602)
    at ZoneTask.invokeTask [as invoke] (zone.js:503)
    at p (zone.js:1540)
defaultErrorLogger @ core.es5.js:1020
ErrorHandler.handleError @ core.es5.js:1080
next @ core.es5.js:4503
t.object.i @ core.es5.js:3635
SafeSubscriber.__tryOrUnsub @ Subscriber.js:246
SafeSubscriber.next @ Subscriber.js:193
Subscriber._next @ Subscriber.js:132
Subscriber.next @ Subscriber.js:96
Subject.next @ Subject.js:63
EventEmitter.emit @ core.es5.js:3621
(anonymous) @ core.es5.js:3912
ZoneDelegate.invoke @ zone.js:392
Zone.run @ zone.js:142
NgZone.runOutsideAngular @ core.es5.js:3844
onHandleError @ core.es5.js:3912
ZoneDelegate.handleError @ zone.js:396
Zone.runGuarded @ zone.js:158
(anonymous) @ zone.js:702
o.microtaskDrainDone @ zone.js:707
drainMicroTaskQueue @ zone.js:610
ZoneTask.invokeTask @ zone.js:503
p @ zone.js:1540
h @ zone.js:1577

**Comment by saket424** [comment]
My federation with other matrix homeservers works and I have set an SRV record.
My nginx configuration relating to matrix looks as follows

        location /_matrix {
                proxy_pass http://localhost:8008;
                proxy_set_header X-Forwarded-For $remote_addr;
        }

        location /widgets {
                proxy_pass http://localhost:8184;
                proxy_set_header X-Forwarded-For $remote_addr;
        }
        location /api {
                proxy_pass http://localhost:8184;
                proxy_set_header X-Forwarded-For $remote_addr;
        }
        location /riot {
                proxy_pass http://localhost:8184;
                proxy_set_header X-Forwarded-For $remote_addr;
        }
        location /js {
                proxy_pass http://localhost:8184;
                proxy_set_header X-Forwarded-For $remote_addr;
        }
        location /css {
                proxy_pass http://localhost:8184;
                proxy_set_header X-Forwarded-For $remote_addr;
        }

**Comment by turt2live** [comment]
This is due to https://github.com/angular/angular/issues/20752

**Comment by saket424** [comment]
@turt2live ,
Many thanks. Updating the rxjs version to 5.5.4 fixed it and I see the various integrations loading

anand@Alien15:~/riot-stuff/matrix-dimension$ git diff package.json
diff --git a/package.json b/package.json
index d2e0f3e..3a9d46a 100644
--- a/package.json
+++ b/package.json
@@ -79,7 +79,7 @@
     "raw-loader": "^0.5.1",
     "reflect-metadata": "^0.1.10",
     "rimraf": "^2.6.1",
-    "rxjs": "^5.2.0",
+    "rxjs": "^5.5.4",
     "sass-loader": "^6.0.3",
     "shelljs": "^0.7.8",
     "style-loader": "^0.18.2",
