### ISSUE TITLE
TradingView widget

### ISSUE THREAD

**Issue by turt2live** [turt2live/matrix-dimension#132]

**Comment by MTRNord** [comment]
Widget API: https://www.tradingview.com/widget/advanced-chart/

**Comment by turt2live** [comment]
The one Scalar is using is actually https://www.tradingview.com/widget/symbol-overview/

**Comment by turt2live** [comment]
Type: `m.tradingview`
Data fields: 
* `exchange`
* `symbol`
* `dateRange`

Pulled from proposed spec: https://docs.google.com/document/d/1v88ZchW-_Dlp5deF1zf5g2FU9Jw8Hwqj28Ms0m4Kp2Q/edit

**Comment by Ashaman-** [comment]
How much effort is involved in completing this particular widget? I may be interested in sponsoring it with a bounty in the very near future, so I'm trying to get an idea of what you might consider a reasonable offer.

**Comment by turt2live** [comment]
Added in https://github.com/turt2live/matrix-dimension/commit/ea834d826a661a18bdc71311fa8f78225ec3130b
