### ISSUE TITLE
Spotify widget

### ISSUE THREAD

**Issue by turt2live** [turt2live/matrix-dimension#133]

**Comment by MTRNord** [comment]
Propably makes sense to use this: https://developer.spotify.com/technologies/widgets/spotify-play-button/

**Comment by turt2live** [comment]
I'm not sure what Modular uses, but it looks like this:
![image](https://user-images.githubusercontent.com/1190097/33851001-e2562666-de72-11e7-8a3b-33725159a235.png)

**Comment by turt2live** [comment]
Looks like they're using the official widgets: https://developer.spotify.com/technologies/widgets/examples/

**Comment by turt2live** [comment]
Type: `m.spotify`
Data fields:
* `uri`

From proposed spec: https://docs.google.com/document/d/1v88ZchW-_Dlp5deF1zf5g2FU9Jw8Hwqj28Ms0m4Kp2Q/edit#

**Comment by turt2live** [comment]
Added in https://github.com/turt2live/matrix-dimension/commit/52708afa7c02b54e334a2cdee835c7f9253b2c29
