### ISSUE TITLE
Add CircleCI integration (self hosted)

### ISSUE THREAD

**Issue by MTRNord** [turt2live/matrix-dimension#137]
This is a issue to handle after my go-neb PR gets merged (https://github.com/matrix-org/go-neb/pull/213) (or maybe after the upstream go-neb got updated)

**Comment by MTRNord** [comment]
@turt2live Is request:bot correct? The PR is about the webhook stuff like the Github notifications. (are these integrations even supported by dimension?)

**Comment by turt2live** [comment]
It's technically a bot, like the RSS bot. Travis CI is implemented in Dimension, but has poor UX (https://github.com/turt2live/matrix-dimension/issues/98) - it's also technically a bot.

"Bot" is kinda the dumping ground for "not anything else".

**Comment by MTRNord** [comment]
@turt2live ah ok 👍

**Comment by turt2live** [comment]
I'm demoting this to just self-hosted support for now. matrix.org historically has taken a while to deploy the new go-neb version, and they take even longer to get the thing in scalar. When it's in scalar, a new issue can be opened for supporting that.

**Comment by MTRNord** [comment]
No problem I propably make a pr as soon as I finish the main pr at go-neb :)

**Comment by turt2live** [comment]
repurposing this to track this for "self-hosted go-neb"

**Comment by turt2live** [comment]
go-neb PR was closed for this :(

**Comment by MTRNord** [comment]
Sadly wasnt able to maintain it further. And that pr doesn't seemed to be merged anytime anyway.
