### ISSUE TITLE
Kitty Sticker Pack

### ISSUE THREAD

**Issue by fabiyamada** [turt2live/matrix-dimension#172]
Hello!
I created two packs with 15 stickers with the theme of "kitties"; I am sending this message as we talked on Riot :) 
Here is the link to all the files: https://drive.google.com/drive/folders/1P5pM7t-XU3lPIgMdCApFieNO42h00Yd8?usp=sharing

Also here is a sample of the stickers:

![image](https://user-images.githubusercontent.com/33674731/39091590-e43f329e-45b3-11e8-9f5f-c04e91ece759.png)

Thank you so much for letting me be part of the project!

**Comment by turt2live** [comment]
Thank you so much! When Dimension gets support for stickers (in the next couple months) I'll be sure to include this sticker pack (part of #156). I'll close this for now and use #156 to track the addition of this pack.
