### ISSUE TITLE
Proposal For Copywriting

### ISSUE THREAD

**Issue by ewuoso** [turt2live/matrix-dimension#173]
Hello i went through your project and i want to say it is very nice. However i noticed you are missing out some important details like gaq, about us and privacy policy which users will be looking forward too. If you dont mind i can write that for you

contact me
email ewuosoolusesi@gmail.com

steemit.com/@ewuoso

**Comment by turt2live** [comment]
All of this information is somewhat dependent on each individual deployment, unfortunately. Google Analytics won't be added to Dimension at this time either.

It's best if people (including myself) hosting Dimension for the public to use have a prominent privacy policy and contact area that users can find.
