### ISSUE TITLE
Sticker picker is not mobile friendly

### ISSUE THREAD

**Issue by turt2live** [turt2live/matrix-dimension#193]
Related: #59 

![screenshot_20180606-085528](https://user-images.githubusercontent.com/1190097/41046529-cffb1956-6967-11e8-9301-3f2ddde45aa4.png)

**Comment by dali99** [comment]
I get this on desktop too FWIW

**Comment by turt2live** [comment]
If you're getting it on desktop then there's something else going wrong. Pop into #dimension:t2bot.io and we'll try and troubleshoot there, although please be patient as replies might not be immediate.

**Comment by turt2live** [comment]
Duplicate of https://github.com/turt2live/matrix-dimension/issues/59

(basically)
