### ISSUE TITLE
"Internal server error" when using with Synapse on localhost

### ISSUE THREAD

**Issue by z3ntu** [turt2live/matrix-dimension#208]
I haven't set up any of the points mentioned in the [readme](https://github.com/turt2live/matrix-dimension#could-not-contact-integrations-server-error), so it not working is expected, but I think a more graceful handling of the register endpoint would be good.

**Comment by turt2live** [comment]
Internal server error usually means there was a stacktrace in the logs - what was it?

**Comment by z3ntu** [comment]
I was trying it with the Riot instance hosted at t2bot.io and the response there is just
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Internal Server Error</pre>
</body>
</html>
```

**Comment by turt2live** [comment]
Oh, I see what the issue is now. It looks like it tries to resolve federation and then fails horribly at it.

**Comment by turt2live** [comment]
unhelpful @turt2live didn't post a stack trace many months ago >.> 

I'm assuming this is fixed, if it isn't then please open a new issue. There's been a major rework to how federation works between then and now.
