### ISSUE TITLE
Sticker picker is not changed when migrating from Scalar to Dimension

### ISSUE THREAD

**Issue by turt2live** [turt2live/matrix-dimension#222]
Due to https://github.com/vector-im/riot-web/issues/7547

(this is just the Dimension bug to track that issue)

**Comment by almereyda** [comment]
Indeed, an unhelpful `Forbidden` in monospace font is being displayed.

Going to Dimension's integration view, following the "Looking for your stickers?" link and enabling a sticker pack - will not show it immediately, but as expected after reload.

**Comment by turt2live** [comment]
Should be fixed in an upcoming Riot release
