### ISSUE TITLE
Sticker previews don't load when run behind an nginx reverse proxy

### ISSUE THREAD

**Issue by shawnanastasio** [turt2live/matrix-dimension#240]
When run behind an nginx reverse proxy, my Riot client is unable to load any sticker previews from dimension. After clicking on a sticker it displays properly, though.

The server log is filled with the following error:
```
Feb-16-2019 00:29:29.833 -06:00 info [Webserver] Incoming request: GET /api/v1/scalar/account?scalar_token=redacted
Error: Can't set headers after they are sent.
    at SendStream.headersAlreadySent (/home/synapse/matrix-dimension/node_modules/send/index.js:390:13)
    at SendStream.send (/home/synapse/matrix-dimension/node_modules/send/index.js:618:10)
    at onstat (/home/synapse/matrix-dimension/node_modules/send/index.js:730:10)
    at FSReqWrap.oncomplete (fs.js:153:5)
```

My nginx reverse proxy configuration is as follows:
```
  server {
     listen 443 ssl;
     server_name dimension.anastas.io;

     ssl on;
     ssl_certificate <redacted>.pem;
     ssl_certificate_key <redacted>.pem;
     ssl_session_timeout 5m;
     ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
     ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
     ssl_prefer_server_ciphers on;
     ssl_session_cache shared:SSL:10m;

     location / {
        gzip off;
        client_max_body_size 50M;
    	proxy_set_header X-Forwarded-For $remote_addr;
        proxy_pass http://<local ip redacted>:8184;
     }
  }
```

**Comment by vmario89** [comment]
having the same problem here with apache reverse proxy
![grafik](https://user-images.githubusercontent.com/5631071/53250694-36578380-36bb-11e9-88ec-936f7fbbbf2c.png)

![grafik](https://user-images.githubusercontent.com/5631071/53250720-41121880-36bb-11e9-97be-5fc24faa62dd.png)

![grafik](https://user-images.githubusercontent.com/5631071/53250732-45d6cc80-36bb-11e9-8052-c152ac785b64.png)

**Comment by vmario89** [comment]
sexy. i solved it. i did a wrong url config in config/production.yaml

In my case i messed up sub domain names. I ended in a working environment by using homeserver URL for the following things:

homeserver:
  name: "matrix.domain.tld"
  clientServerUrl: "https://matrix.domain.tld"
  federationUrl: "https://matrix.domain.tld:8448"

At first i thought it should be https://dimension.domain.tld (where i point my apache vhost to)

![grafik](https://user-images.githubusercontent.com/5631071/53277262-4f842280-3703-11e9-8d7c-1e8a3edaaeeb.png)

regards and many many thanks for this great and pretty integration server!

**Comment by NullIsNot0** [comment]
I solved it by allowing my synapse server outgoing connections to matrix.t2host.io:8448. Previously these connections was denied by network firewall.

**Comment by turt2live** [comment]
Closing in favour of https://github.com/turt2live/matrix-dimension/issues/247
