### ISSUE TITLE
Wikipedia via go-neb

### ISSUE THREAD

**Issue by vmario89** [turt2live/matrix-dimension#243]
Hi, i am running matrix-dimension and matrix-goneb. I configured the wikipedia bot in matrix-goneb to be named @go-neb:matrix.domain.tld which works and i can invite him. But i use matrix-dimension to integrate Wikipedia, @_neb_wikipedia:matrix.org is used instead. I did not find any way to reconfigure this. Is there an option maybe?

![grafik](https://user-images.githubusercontent.com/5631071/53840887-a9a2a480-3f9b-11e9-8ba5-e93ea1f6c415.png)

the config.yaml of go-neb looks simply the following:
![grafik](https://user-images.githubusercontent.com/5631071/53840944-cb9c2700-3f9b-11e9-9ed4-fd0bc616878b.png)

regards and thanks for info, Mario

**Comment by turt2live** [comment]
In the admin panel is a "go-neb" section where you can configure the bots. It's worth noting that Dimension itself will manage the bots, so the bot you've configured in go-neb will not be used.

**Comment by turt2live** [comment]
I'm assuming the suggestion 19 days ago fixed it. If not, please open a new issue with more detail.
