### ISSUE TITLE
The Jitsi Widget Fails to Load

### ISSUE THREAD

**Issue by Cadair** [turt2live/matrix-dimension#249]
I gets past the "Join the Videoconference" screen and then I get a bunch of the following errors in my Riot console:

```
[modules/settings/Settings.js] <u>:  DOMException: "The operation is insecure." Logger.js:124:12
	i Logger.js:124
	u Settings.js:126
	get callStatsUserName Settings.js:20
	e AnalyticsAdapter.js:98
	<anonymous> AnalyticsAdapter.js:337
	<anonymous> EventEmitterForwarder.js:38
n21Webpackicon
```

```
TypeError: "this.state.store is undefined"
	value BaseApp.js:95
wi14React	<anonymous> index.web.js:24
 react-dom.production.min.js:179:139
```
```
SecurityError: The operation is insecure. app.bundle.min.js:1
```

There isn't anything in the dimension logs that I can see.

**Comment by turt2live** [comment]
@Cadair this seems to be caused by strict CORS policies from the web server. The errors look like they are coming from Jitsi, which runs in an iframe in the widget's iframe ( `[ Riot [ Widget [ Jitsi ]]]` ). Do you have any strange policies on either Riot or Dimension that could cough up some CORS-related errors like this?

**Comment by Cadair** [comment]
I don't think so. There again I am not entirely sure where to look. There is nothing in the headers of a GET request to either the riot or dimension domain which looks off. How would you suggest I check for anything out of the ordinary?

**Comment by turt2live** [comment]
It'd probably be something you'd explicitly configure on the server side, but it sounds like that's not a thing that happened. Can I get a url to the riot+dimension instance causing problems so I can poke around? (Over private chat is fine if here doesn't feel appropriate)

**Comment by Cadair** [comment]
This seemed to be a combination of third party cookie settings and bad headers.
