### ISSUE TITLE
Can you please tag your Docker images?

### ISSUE THREAD

**Issue by NullIsNot0** [turt2live/matrix-dimension#253]
Your project's Docker image is used in https://github.com/spantaleev/matrix-docker-ansible-deploy. Now it is configured to use `turt2live/matrix-dimension:latest`. It would be better to use some tested (with integration in `spantaleev/matrix-docker-ansible-deploy`) image before switching to newer build of your project's image. Can you please add tags to your Docker builds?

**Comment by turt2live** [comment]
There's not been a version 1 release of Dimension yet, but once there is it will be tagged. The images are tested by at least myself though on t2bot.io.
