### ISSUE TITLE
avoid fetching remote resources

### ISSUE THREAD

**Issue by airblag** [turt2live/matrix-dimension#256]
I just noticed that loading dimension requests 2 external resources : 

https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css (in web/public/index.html)

Is there a reason not to include it in the source tree of dimension directly ?

and  https://fonts.googleapis.com/css?family=Open+Sans:100|Roboto:300 (in web/style/app.scss)

As far as I unterstand, it downloads the font from google only if it was not found locally. Is it possible to include this font directly in the source tree, or at least the css checking for the font ?

I have no idea of web development, but I always try to avoid informing external services about every click in my infrastructure.

**Comment by turt2live** [comment]
This can absolutely be done, and it certainly should be done within the app rather than going remote.
