### ISSUE TITLE
Remove third party cdn's

### ISSUE THREAD

**Issue by Perflyst** [turt2live/matrix-dimension#270]
At the moment `https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css` is loaded from maxcdn as third party. Also some other CSS files are loaded from third party.
I would prefer to have it locally instead. Is there any need for this third party? I dont think so.

**Comment by turt2live** [comment]
Duplicate of https://github.com/turt2live/matrix-dimension/issues/256
