### ISSUE TITLE
Stickers post multiple times

### ISSUE THREAD

**Issue by Ryonez** [turt2live/matrix-dimension#273]
Running a self hosted dimension and sticker bot.

Even with the sticker bot off, it'll post a sticker you select multiple times.
Normally it'll just do one if it hasn't been used in a while, and switching channels seems to trigger it.
Looks like this:
![image](https://user-images.githubusercontent.com/16157130/55764712-daa55600-5ac0-11e9-9b14-23a45f28a29b.png)

**Comment by tulir** [comment]
I think this was a riot bug and already fixed on develop by matrix-org/matrix-react-sdk#2862

**Comment by turt2live** [comment]
yup, this is a Riot bug. Should be fixed in the next release.

**Comment by Ryonez** [comment]
Ohhhh, that makes so much sense now. Thank you for the correction and link to the correct issue.
