### ISSUE TITLE
federation tester url found on Dimension homepage returns a 404 error

### ISSUE THREAD

**Issue by jeromecc** [turt2live/matrix-dimension#279]
Hello!

Dimension home page suggests testing federation but the link

    ```https://matrix.org/federationtester/api/report```

returns a 404 error

    Not Found
    The requested URL /federationtester/api/report was not found on this server.

Thanks for this amazing project!

**Comment by turt2live** [comment]
It's currently pending a rebuild. See https://twitter.com/matrixdotorg/status/1118979411339022343 for the latest update, and watch Twitter for further updates.
