### ISSUE TITLE
Unable to get access token

### ISSUE THREAD

**Issue by jacotec** [turt2live/matrix-dimension#280]
Following the document to get an access token:

https://t2bot.io/docs/access_tokens/

I definitely do not find a button to get the access token on any of the settings pages. I've tried my self hosted Riot-Web, the Riot desktop app and https://riot.im/app.

Any idea how I can get the token?

**Comment by nimogit** [comment]
In riot web/desktop recent version you'll find it under **settings**->**Help & about** section at the bottom of the page under advanced category (Access Token: <click to reveal>)

**Comment by turt2live** [comment]
Yup, it's also not visibly clickable for some reason but definitely is:

![image](https://user-images.githubusercontent.com/1190097/57151971-7445e780-6d8f-11e9-890d-9004aab9469d.png)

Closing in favour of https://github.com/t2bot/t2bot.io/issues/22
