### ISSUE TITLE
npm install resulting in error 404 for node-sass@4.11.0

### ISSUE THREAD

**Issue by tgurr** [turt2live/matrix-dimension#282]
Trying to follow the install instructions: https://github.com/turt2live/matrix-dimension/blob/master/docs/installing.md
```
$ git clone https://github.com/turt2live/matrix-dimension.git
$ cd matrix-dimension
$ npm install

> node-sass@4.11.0 install /home/test/matrix-dimension/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.11.0/linux-x64-72_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.11.0/linux-x64-72_binding.node": 

HTTP error 404 Not Found
```

**Comment by turt2live** [comment]
Looks like your operating system isn't supported by node-sass - they don't have a release for that architecture, so the 404 is valid.

**Comment by tgurr** [comment]
Ah thanks, I think I undestand the reason now. I'm running node 12.0.0 which only seems to have bindings available in node-sass >= 4.12.0.

**Comment by turt2live** [comment]
Dimension should be fine with that version, so pinning it might work.

**Comment by luccosta** [comment]
Exist a release for that architecture, but in other version, like v4.14.1, and even when I use npm install node-sass@4.14.1 this still try to download the binary from v4.11.0 release.

**Comment by tgurr** [comment]
As the current Dockerfile uses Node.js v14.x and I've just successfully build and ran (just accessing the plain initial website, no actual integration) current master with Node.JS v16.x I'm closing this issue as it appears to be no longer valid.
