### ISSUE TITLE
Docker container not starting

### ISSUE THREAD

**Issue by jcklie** [turt2live/matrix-dimension#301]
When I try to start the docker container, then it crashes immediately:

```
root@leela:/opt/dimension#     docker run -d --name dimension -p 127.0.0.1:8184:8184 -v /opt/dimension:/data turt2live/matrix-dimension
root@leela:/opt/dimension# ls -ll  /opt/dimension/default.yaml 
-rw-r--r-- 1 root root 4012 Aug 22 10:44 /opt/dimension/default.yaml 
root@leela:/opt/dimension# docker logs dimension
cp: can't create '/data/config.yaml': Permission denied
```

`docker ps` does not show it to be running. I also tried to not link `/data` to the host, but that results in the same error. What am I doing wrong?

**Comment by turt2live** [comment]
Looks like the docker container doesn't have permission to access `/opt/dimension` on your system. It needs a volume mounted to operate.

**Comment by jcklie** [comment]
The problem is that the Dockerfile uses a user `node` which cannot write to my folder. The standard docker fix I think would be to create a user on the host, record its uid, change the folder permissions of the container and specify the user on the command line via `docker ... --user <uid> ...`.

**Comment by jcklie** [comment]
This looks like a duplicate of #224 then, closing this!
