### ISSUE TITLE
"Voice call" button in group chats rely on config.json to work

### ISSUE THREAD

**Issue by mrjohnson22** [turt2live/matrix-dimension#307]
With Riot 1.4.0's configurable Integration Managers, it should be assumed that Jitsi calls created by the "Voice call" button (the one with the telephone icon) use the Jitsi domain managed by the Integration Manager.

But, it turns out that calls created in this way don't work at all, as the Jitsi widget appears as completely blank unless Riot's config.json has been configured with "integrations_" URLs pointing to a Dimension instance.

Without a custom config.json (or when using https://riot.im/app/), the Jitsi URL of such a group call has the following path:
`https://<integration_manager_domain>/api/v1/scalar/widgets/jitsi.html`

Meanwhile, with config.json set up, the Jitsi URL has this path instead:
`https://<integration_manager_domain>/widgets/jitsi`

Jitsi calls set up by entering the Integration Manager menu (the one with the four-squares icon) are not affected by this and work just fine, and have the same path as in the case of a modified config.json.

Perhaps this is a case of Riot/Web using bad defaults for Jitsi URLs?

Possibly related to https://github.com/vector-im/riot-web/issues/11030.

**Comment by turt2live** [comment]
This isn't something dimension can fix. The "make a widget" API needs specifying so riot can fix the button - please open an issue on riot-web
