### ISSUE TITLE
Importing stickers from Telegram doesn't work anymore

### ISSUE THREAD

**Issue by turt2live** [turt2live/matrix-dimension#309]
This should probably be a different project anyways

**Comment by PeterCxy** [comment]
as of 2020-01-25 i tested and it seemed to be still working just fine

**Comment by xthursdayx** [comment]
It doesn't work for me (running Dimension as part of the Matrix Ansible stack), but I'm not sure how to figure out why it isn't working. Any tips?

**Comment by TheTimeWalker** [comment]
Weirdly enough, it now works on my end too. I was able to add three sticker packs without issues.

**Comment by turt2live** [comment]
Going to close as fixed then, without testing myself.

**Comment by xthursdayx** [comment]
Still isn't working for me. @TheTimeWalker any chance you could share the sticker pack links you used so I can try to add them? Also, did you make any changes to your dimension or synapse configs?

**Comment by TheTimeWalker** [comment]
No changes, tried it out with:
* Facebook Foxes: https://t.me/addstickers/facebookfoxes
* Facebook Foxes 2: https://t.me/addstickers/facebookfoxes2
* Gentle Rabbit: https://t.me/addstickers/GentleRabbit

**Comment by xthursdayx** [comment]
Weird. Still doesn't work for me. Thanks for the into though.

**Comment by PlanetSmasher** [comment]
We got the same problems as you @xthursdayx 
sadly none of the Stickerpacks work  everytime we get in the journalctl a 404 and in my Browser a 500 HTTP error

**Comment by charludo** [comment]
Bump - and it's really sad! The amount of people I know that stick to Telegram because of their stickers is... Mindboggling.

**Comment by turt2live** [comment]
https://github.com/turt2live/matrix-dimension/issues/364
