### ISSUE TITLE
stickers give 403 forbidden

### ISSUE THREAD

**Issue by smoebody** [turt2live/matrix-dimension#316]
Since shortly i cannot choose from stickers anymore. I can add integrations like jitsi to the room, i can add and remove sticker-packs but i cannot choose a sticker in the conversation.

![image](https://user-images.githubusercontent.com/991327/69988201-78163400-1541-11ea-9a6c-d0e36e8eadd2.png)

also it seems that riot is contacting scalar.vector.im when i click the sticker-icon which is what is returning the 403:
```js
fetch("https://scalar.vector.im/api/widgets/id/9eea8eb8-822c-4060-9b9f-59b6c7aa281e/stickers.html?widgetId=9eea8eb8-822c-4060-9b9f-59b6c7aa281e&parentUrl=https%3A%2F%2Fchat.metaccount.de%2F", {"credentials":"include","headers":{"accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3","accept-language":"de,en;q=0.9,de-DE;q=0.8,en-US;q=0.7","sec-fetch-mode":"nested-navigate","sec-fetch-site":"cross-site","upgrade-insecure-requests":"1"},"referrerPolicy":"no-referrer","body":null,"method":"GET","mode":"cors"});
```

my riot-config has no scalar.vector.im configured so i wonder where this is coming from. any ideas?

**Comment by smoebody** [comment]
i think this is a riot-web issue, opening new one there.

browsing the stickers in riot-android and riot-desktop seems to work (although i dont know why)

**Comment by turt2live** [comment]
Your sticker picker is not a Dimension sticker picker, so this is not a Dimension issue.

**Comment by ZerataX** [comment]
ehm sorry for bringing this up again, but where do I look to troubleshoot this? how do i get back to a dimension sticker picker? this works for me but not a friend of mine on the same riot instance on the same homeserver.

https://chat.dmnd.sh/config.json
https://dmnd.sh/.well-known/client

all look correct to me and the troubleshooter says everything works perfectly, but for my friend the troubleshooter just stays blank and the sticker picker user wants to use vector.im

**Comment by br4nnigan** [comment]
I'm getting this using Element Desktop (how do I change the integration server on the mobile app?)

probably I have misconfigured Dimension.
