### ISSUE TITLE
Mounted Data Folder is Unwriteable

### ISSUE THREAD

**Issue by DarkRider1768** [turt2live/matrix-dimension#319]
We are trying to deploy Dimension in our Kubernetes environment but are hitting snags. It seems that the specified data folder is unwriteable with the current docker image available. We tried jumping into shell for the pod to try and chmod the folder but were unable to do even that. This has worked for other docker images in the past (Synapse runs as 991:991 and requires a little help initially to get to run).

For storage, we are using Longhorn to create highly available storage pods for the cluster. The service has a PVC via Longhorn of 25GB (no sizing information available for Dimension so we just made it huge) so space shouldn't be an issue for a config.yaml file.

The errors that we are receiving:
Docker image ran normally:
```
cp: can't create '/data/config.yaml': Permission denied
```
Docker image ran with entry point /bin/sh:
```
bash-4.4$ ls -lah
total 72
drwxr-xr-x    1 root     root        4.0K Dec 11 22:22 .
drwxr-xr-x    1 root     root        4.0K Dec 11 22:22 ..
-rwxr-xr-x    1 root     root           0 Dec 11 22:22 .dockerenv
drwxr-xr-x    1 root     root        4.0K Dec  9 22:14 bin
drwxr-xr-x    3 root     root        4.0K Dec 11 21:46 data
drwxr-xr-x    5 root     root         380 Dec 11 22:22 dev
-rwxr-xr-x    1 root     root         426 Dec  9 22:32 docker-entrypoint.sh
drwxr-xr-x    1 root     root        4.0K Dec 11 22:22 etc
drwxr-xr-x    1 root     root        4.0K May 29  2019 home
drwxr-xr-x    1 root     root        4.0K Dec  9 22:14 lib
drwxr-xr-x    5 root     root        4.0K May  9  2019 media
drwxr-xr-x    2 root     root        4.0K May  9  2019 mnt
drwxr-xr-x    1 root     root        4.0K May 29  2019 opt
dr-xr-xr-x  572 root     root           0 Dec 11 22:22 proc
drwx------    1 root     root        4.0K May 29  2019 root
drwxr-xr-x    1 root     root        4.0K Dec 11 22:22 run
drwxr-xr-x    1 root     root        4.0K Dec  9 22:15 sbin
drwxr-xr-x    2 root     root        4.0K May  9  2019 srv
dr-xr-xr-x   13 root     root           0 Dec 11 22:22 sys
drwxrwxrwt    1 root     root        4.0K Dec  9 22:30 tmp
drwxr-xr-x    1 root     root        4.0K Dec  9 22:32 usr
drwxr-xr-x    1 root     root        4.0K May  9  2019 var
bash-4.4$ mkdir /data/test
mkdir: can't create directory '/data/test': Permission denied
bash-4.4$ chmod 777 /data
chmod: /data: Operation not permitted
bash-4.4$ 
```

**Comment by turt2live** [comment]
I'm not sure what you would expect from the container - it's supposed to be mounted as a volume to somewhere. Simply starting the container and opening bash within it won't help you unless it's been mapped to a real storage location on the host.

Permission errors are almost always a problem with the host machine, not the image.

**Comment by DarkRider1768** [comment]
And it was mounted as a volume... Longhorn created a .img file which was mounted to the host OS and then Kubernetes uses docker to pass that volume through to the container.

This works (by design, it's literally the way Longhorn works) for every other container we've spun up. A few images required some hand holding because they modify the user/group performing the execution on runtime but otherwise it works solid. I'm not sure where the disconnect is with this image because pretty much every command fails at shell, which is not the case for other images.

**Comment by turt2live** [comment]
This image is fully intended to be run as a boring Docker container and not as an image... I'm not familiar with Longhorn at all, but it sounds like it is doing things to the image I can't reasonably support with this project.

If it doesn't work as a plain Docker container, then we have a bug.

**Comment by DarkRider1768** [comment]
Longhorn does absolutely nothing to the image, it's just a completely separate storage piece used by Kubernetes. Kubernetes is just orchestration for docker so it's still running on boring docker, there is just software running parallel to handle scheduling and availability.

This is definitely an issue with the image. I just fired up Synapse and jumped to shell and ran the exact same commands I ran with the Dimension image and they all completed without fail. I'm noticing when running whoami that it's coming back with a username called node rather than root. This is where the issue lies.

I forced the container to run as uid 0 and managed to get root access from shell. I then ran chown 1000:1000 on the data folder and it seems to have gone through. You should probably take a look at how Synapse is handling the uid in it's image, it's more straight forward from a diagnostics standpoint.

**Comment by turt2live** [comment]
Sounds like this is a duplicate of https://github.com/turt2live/matrix-dimension/issues/224 then.
