### ISSUE TITLE
build error in ./web/style/app.scss

### ISSUE THREAD

**Issue by duperray** [turt2live/matrix-dimension#327]
Hi, 
I cannot build:

> ERROR in ./web/style/app.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
/srv/matrix-dimension/node_modules/css-loader/dist/plugins/postcss-icss-parser.js:34
      accumulator[normalizedUrl] = { ...accumulator[normalizedUrl],
                                     ^^^

**Comment by turt2live** [comment]
Please provide more information, as the logs you've supplied do not explain the problem at all.

**Comment by turt2live** [comment]
Also, let's debug in #dimension:t2bot.io please.
