### ISSUE TITLE
No URL Field in the "Add Sitcker Packs" box

### ISSUE THREAD

**Issue by PolynomialDivision** [turt2live/matrix-dimension#328]
I used the [Stickerbot](https://t2bot.io/stickerbot/) to create a new Sticker Pack.
Now, I want to import it, but I can not find

    Paste the URL the bot gave you into the "Add Sitcker Packs" box.

Or, do I have to host my own dimension server?

**Comment by turt2live** [comment]
It would be in the dimension side of things (open dimension like you're adding a bridge, then click on the sticker packs link) and not the sticker picker. It can be disabled by the admin, and is only a feature of dimension.
