### ISSUE TITLE
integration problem - 

### ISSUE THREAD

**Issue by felipe157775** [turt2live/matrix-dimension#334]
Hi, 2 days without sleep, could U help me? THANKS!!! 

Apr-1-2020 21:31:46.313 -03:00 info [BotSdk-MatrixLiteClient (REQ-1)] GET https://dimension.all.com.br/_matrix/client/r0/account/whoami
Apr-1-2020 21:31:46.480 -03:00 info [BotSdk-MatrixLiteClient (REQ-1 RESP-H400)] {"0":"<","1":"!","2":"D","3":"O","4":"C","5":"T","6":"Y"

  body:
   '<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n<title>Error</title>\n</head>\n<body>\n<pre>Bad Request</pre>\n</body>\n</html>\n' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! matrix-dimension@1.0.0 start:app: `npm run-script build && node build/app/index.js`
npm ERR! Exit status 1
npm ERR! 

====== INFOS ====================

0) Matrix
  - port: 8448
    type: http
    tls: true
    bind_addresses: ['200.218.XXX.XXX']
    resources:
      - names: [federation]
        x_forwarded: false
  # Unsecure HTTP listener: for when matrix traffic passes through a reverse proxy
  # that unwraps TLS.
  - port: 8008
    type: http
    x_forwarded: true
    bind_addresses: ['127.0.0.1']
    resources:
      - names: [client, federation]
        compress: false

1) production.yaml

web:
  port: 8184
  address: '127.0.0.1'

# Homeserver configuration
homeserver:
  name: "matrix.all.com.br"
  # The URL that Dimension, go-neb, and other services provisioned by Dimension should
  # use to access the homeserver with.
  clientServerUrl: "https://dimension.all.com.br"
 
2) NGIX
1A) /etc/nginx/sites-enabled/dimension
server {
    server_name dimension.all.com.br;
    listen 443 ssl;
    listen [::]:443 ssl;

    ssl_certificate /etc/letsencrypt/live/dimension.all.com.br/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/dimension.all.com.br/privkey.pem;

    root /var/www/html/;
    index index.html;

    location / {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://localhost:8184;
    }
}

1B) /etc/nginx/sites-enabled/matrix
server {
       listen 80;
       server_name matrix.all.com.br;
       return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name matrix.all.com.br;

    ssl_certificate /etc/letsencrypt/live/matrix.all.com.br/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/matrix.all.com.br/privkey.pem;

    # If you don't wanna serve a site, comment this out
    root /var/www/html;
    index index.html index.htm;

    location /_matrix {
      proxy_pass http://127.0.0.1:8008;
      proxy_set_header X-Forwarded-For $remote_addr;
    }
}

**Comment by turt2live** [comment]
Please use #dimension:t2bot.io for support.
