### ISSUE TITLE
matrix-dimension do not start with curious error message

### ISSUE THREAD

**Issue by ralfi** [turt2live/matrix-dimension#335]
Hi, trying to start selfhosted matrix-dimension tells me 

error [index] The access token configured for dimension belongs to a user which is also a known user to Diemnsion. This usually indicates that the access token is not a dedicated user account for dimension. To prevent potential confusion ... Dimension will refuse to start

Error: Access token belongs to a real user. See log for details

 at /home/node/matrix-dimension/build/app/index.js:40:19
 at Generator.next (<anonymous>)
 at fulfilled (home/node/matrix-dimension/build/app/index.js:4:58)

using turt2live/matrix-dimension:latest docker image

Sometimes it helps to remove the config,yaml and the database but i really don know whats happened here. Mmmh.

**Comment by turt2live** [comment]
Please use #dimension:t2bot.io for support.

**Comment by ralfi** [comment]
Sorry, was my mistake. Because i use a a access token wihout anonymus browser session.
