### ISSUE TITLE
Can't build matrix-dimesion

### ISSUE THREAD

**Issue by Russe1503** [turt2live/matrix-dimension#341]
Hey,

I try to install matrix-dimesion on a Linux Ubuntu 18.04.4 LTS, but it doesn't work.
Node v10.20.1
npm 6.14.4

After Step 2: Configuring Dimension I try to use NODE_ENV=production npm run start:app, but I got error msg.

That is the output of the log file

`0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'start:app' ]
2 info using npm@6.14.4
3 info using node@v10.20.1
4 verbose run-script [ 'prestart:app', 'start:app', 'poststart:app' ]
5 info lifecycle matrix-dimension@1.0.0~prestart:app: matrix-dimension@1.0.0
6 info lifecycle matrix-dimension@1.0.0~start:app: matrix-dimension@1.0.0
7 verbose lifecycle matrix-dimension@1.0.0~start:app: unsafe-perm in lifecycle true
8 verbose lifecycle matrix-dimension@1.0.0~start:app: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/matrix-dimension/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle matrix-dimension@1.0.0~start:app: CWD: /root/matrix-dimension
10 silly lifecycle matrix-dimension@1.0.0~start:app: Args: [ '-c', 'npm run-script build && node build/app/index.js' ]
11 silly lifecycle matrix-dimension@1.0.0~start:app: Returned: code: 1  signal: null
12 info lifecycle matrix-dimension@1.0.0~start:app: Failed to exec start:app script
13 verbose stack Error: matrix-dimension@1.0.0 start:app: `npm run-script build && node build/app/index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid matrix-dimension@1.0.0
15 verbose cwd /root/matrix-dimension
16 verbose Linux 4.15.0-96-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "start:app"
18 verbose node v10.20.1
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error matrix-dimension@1.0.0 start:app: `npm run-script build && node build/app/index.js`
22 error Exit status 1
23 error Failed at the matrix-dimension@1.0.0 start:app script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`
I hope anybody can help me. 
thank you in advance!

**Comment by turt2live** [comment]
Please use #dimension:t2bot.io for support.
