### ISSUE TITLE
How to set the default configuration values of the jitsi widget?

### ISSUE THREAD

**Issue by cnvandijk** [turt2live/matrix-dimension#344]
Considering the use case of deploying a self-hosted dimension instance via a [playbook](https://github.com/spantaleev/matrix-docker-ansible-deploy), is there a way to set the default configuration values of the jitsi widget before deploying the instance? At the moment it looks like the only way is for an admin user to set this via the configuration dialog of a *running* instance. Or something in [src/db/migrations/](https://github.com/turt2live/matrix-dimension/blob/293097f6fbf23eaf311764a0e932696408cb30d8/src/db/migrations/20171218203245-AddWidgets.ts#L74).

There is of course `jitsi.preferredDomain` in riot-web's config, and `im.vector.riot.jitsi.preferredDomain` in `.well-known/matrix/client`, but dimension does not use either of these.

**Comment by turt2live** [comment]
It's not currently possible outside of the UI. 

Closing in favour of https://github.com/turt2live/matrix-dimension/issues/345
