### ISSUE TITLE
Blocked by X-Frame-Options Policy

### ISSUE THREAD

**Issue by mxc** [turt2live/matrix-dimension#348]
Hi,
I have set up  matrix-dimension using the base metal approach. It is behind apache using proxy pass. I get the error "Blocked by X-Frame-Options Policy" when I try to access the dimension site from Riot web application.

The target page opens fine if I write click and select "this frame"->"Open frame in new tab"/

I have checked and there are no headers being set in the nginx or apache proxy front-end. The error appears to come from src/api/dimension/DimensionWidgetService.ts

In Firefox developer view I can see that a X-Frame-Options header is sent by matrix-dimension. I had to add "Header unset X-Frame-Options" to apache config to get it to work.

Have a set up things incorrectly?

**Comment by turt2live** [comment]
Dimension doesn't send that header. Please use #dimension:t2bot.io for support.
