### ISSUE TITLE
Per user stickerpacks

### ISSUE THREAD

**Issue by Bubu** [turt2live/matrix-dimension#363]
(I fear that this functionality is actually already there and I'm just missing something, or maybe it needs a bit of plumbing to fully work)

Stickerpacks are currently manager by the dimension admin (at least that's how I got it to work, there's also an import url field in the user-view but I can't figure out how that works at all). So as an admin I import sticker packs from telegram which users can then enable to for them to use.

This created two problems:
* Users need to ask the admin to add a new stickerpack
* All sticker packs imported by the admin are public to everyone (because of #110 they are actually public to the world)

Would it be possible to let every user add their own sticker-packs that are visible just for them instead?

**Comment by turt2live** [comment]
This exists already:
![image](https://user-images.githubusercontent.com/1190097/86522917-35437400-be22-11ea-81e5-2eeb85e12429.png)

**Comment by Bubu** [comment]
But if I paste a `https://t.me/addstickers/<ABC>` url into that field it just instantly gives me an error: "Error adding Stickerpack"

(That's what I meant with I can't figure out how this works)

**Comment by turt2live** [comment]
It doesn't support Telegram sticker packs for security reasons, but it does support sticker packs created with the helper bot (`@stickers:t2bot.io` in this case - this is configurable).
