### ISSUE TITLE
node_modules still ending up in production desipite being named in .docker_ignore

### ISSUE THREAD

**Issue by mayhd3** [turt2live/matrix-dimension#376]
Using matrix-docker-ansible-deploy https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/667#event-3880171274 and running ncdu on /var/lib/docker/overlay2 reveals matrix-dimension has a huge node_modules folder in it; angular alone is 500mb. Opening a docker shell and deleting it does not seem to remove it from overlay2. I could risk deleting it manually, but I am afraid.

**Comment by turt2live** [comment]
it needs these to run, so they can't be excluded, sorry.
