### ISSUE TITLE
Document and support widgets (when available)

### ISSUE THREAD

**Issue by turt2live** [turt2live/matrix-dimension#38]
https://github.com/matrix-org/matrix-react-sdk/pull/1068

**Comment by turt2live** [comment]
Original PR has been amended: https://github.com/matrix-org/matrix-react-sdk/pull/1201

**Comment by Kegsay** [comment]
Widgets are documented [here](https://docs.google.com/document/d/1TiWNDcEOULeRYQpkJHQDjgIW32ohIJSi5MKv9oRdzCo/edit), but will remain in flux. That document is the source of truth though.

**Comment by turt2live** [comment]
Thanks for the document, didn't realize there was one. 

Dimension as a project is more or less on hold until the integrations stuff is more stable/capable.
