### ISSUE TITLE
Feature request: introduce a "stable" tag to the Docker container

### ISSUE THREAD

**Issue by briankendall** [turt2live/matrix-dimension#432]
Hello! I was just trying to install Dimension via matrix-docker-ansible-deploy and hit a brick wall as Dimension failed to start up due to #431. After a few hours of digging into it I realized that the error came from a coding error in Dimension itself that had been introduced recently.

Given the Dimension docker repo only has one usable tag, `latest`, would you consider adding a `stable` tag that gets pushed up whenever there's a reasonable assurance that the software is in a good working state? Otherwise anytime that someone pulls or updates their Docker image, they could suddenly find themselves in a mess and potentially lose hours of time due to recently added unstable code.

**Comment by turt2live** [comment]
Dimension deliberately does not have releases at the moment as it is still considered in development, thus there is no stable channel to actually release upon.

Once Dimension has actual releases, stable images will be more or less available.

**Comment by briankendall** [comment]
Okay, that's reasonable. Best of luck getting to your first release! I look forward to it.
