### ISSUE TITLE
Sticker pack not being loaded into element-web

### ISSUE THREAD

**Issue by altsalt** [turt2live/matrix-dimension#440]
Hi, I'm having issues loading a sticker pack created with sticker bot. When copying the URL into the box and clicking add stickerpack, it does appear with a green slider indicating that it is enabled. However, when I close the Dimension window, the add sticker box remains open with the message "You don't currently have any stickerpacks enabled". Closing that box and re-opening it does not have any effect. Nor does disabling/re-enabling the slider. I've tried this with element-web on both Firefox and Chromium, and on two separate homeservers setup using matrix-docker-ansible-deploy, with the same results.

[console log](https://gist.github.com/altsalt/90fd80a3c8cffd2084f241f0a27ec6b1) (updated to include complete process after `clear cache and reload`)
[journal log](https://gist.github.com/altsalt/c2ed05d7ae6fff472958c1eef15e0a37)

I realize there are a number of open issues that may be pertinent to this. This one appears more active and often pointed towards:
https://github.com/vector-im/element-web/issues/14315

**Comment by opencooking** [comment]
I can second this issue @altsalt 
stickers are not being shown up in the sticker select thing or what you want to call  it
but are enabled and selected in Dimension itself

so far I've not been able to produce any logs which seem pertinent to the problem sadly
I am still investigating though and will update here if I find anything

**Comment by DemonWareXT** [comment]
I can second this issue @altsalt
stickers are not being shown up in the sticker select thing or what you want to call it
but are enabled and selected in Dimension itself

so far I've not been able to produce any logs which seem pertinent to the problem sadly
I am still investigating though and will update here if I find anything

**Comment by mibmo** [comment]
I'm also having this issue. On mobile though, I can choose to use a different widget for stickerpicking and upon doing so it works on mobile but I get some 5XX error (likely forbidden; IDR) when trying to use the widget on PC (both element-web and element-desktop).

**Comment by phorcys420** [comment]
> 
> 
> I can second this issue @altsalt stickers are not being shown up in the sticker select thing or what you want to call it but are enabled and selected in Dimension itself
> 
> so far I've not been able to produce any logs which seem pertinent to the problem sadly I am still investigating though and will update here if I find anything

same here, running [turt2live/matrix-dimension:latest](https://hub.docker.com/layers/turt2live/matrix-dimension/latest/images/sha256-740b8bf3ca861feda7af10fb3e3752de5ecd7b1b31a2664ab98bae4bee74ef7c?context=explore), on a federated Synapse v1.46.0 server (matrix.phorcys.net).

![image](https://user-images.githubusercontent.com/57866459/142608907-dfe81a77-67f2-4ee4-8df5-80eb1395b68b.png)
![image](https://user-images.githubusercontent.com/57866459/142608949-e97de1de-57c6-4a1f-a125-f53f40e6d2cf.png)

I think the easiest (functional-est) solution is just to switch to [maunium's sticker picker](https://mau.dev/maunium/stickerpicker) for the time being.

**Comment by Vibeshibe** [comment]
Can report the same issue here.

**Comment by Vibeshibe** [comment]
Ok so after playing a bit around, I managed to get it working. This just consisted of me spamming reload on element web and restarting the client over and over until it asked me "Do you trust this integration manager, dimension.example.com" I clicked yes, then removed the widget as it turned to a 504, then clicked add stickers again, enabled a sticker pack and bam it worked for me. I did check the logs of dimension and see some particular errors here I cannot grasp the context of. I will attach them for you all to check out, around the part where it checks the bridges is when it started working for me. The requests after that are from users on my home-server who still cannot use the stickerpicker.
[_dimension_logs.txt](https://github.com/turt2live/matrix-dimension/files/7594639/_dimension_logs.txt)
r.

**Comment by vquicksilver** [comment]
I am seeing the same issue here using Element web 1.9.8, dimension v1.0.0 and synapse 1.49.0 on and un-federated server.

I am able to import stickerpacks from Telegram, and I can see the 4 default packs as well (So I can toggle enable/disable them from the Dimension UI) but whenever I toggle one on of them in any room where I have proper permissions I get the following messages on the browser console:

```
Action:set_widget failed with message: Missing room_id in request
Failed to check for Dimension sticker picker
```

The failure seems to stem from the async method addWidget() in the try/catch block (stickerpicker.component.ts), I have no idea of javascript/typescript but it seems like the UI is not sending the room_id somehow, and in the end the stickerpacks are not enabled. 

Note that I can for example create a youtube widget in the room successfully, so it seems to be related just to the stickerpacks. I am willing to provide whatever logs you need to further debug the issue, just let me know what you need.

**Comment by acheng-floyd** [comment]
look at this: https://github.com/matrix-org/matrix-react-sdk/pull/7448
it's the problem of matrix-react-sdk, not the matrix-dimension. I compiled element-web using this branch "bink:fix/set-widget-action-room-id-check", then stickers picker is working now!
![image-20211228184955552](https://raw.githubusercontent.com/acheng-floyd/markdown_pic/master/img/202112281850874.png)

**Comment by DemonWareXT** [comment]
hey everyone, as of patch 1.9.9 Element works with stickers without the manual fix
thanks @acheng-floyd  :)
