### ISSUE TITLE
Can't start Dimension: Error: Access token belongs to a real user.

### ISSUE THREAD

**Issue by Grummeltier** [turt2live/matrix-dimension#473]
I've installed Dimension on my own Homeserver with the spantaleev/matrix-docker-ansible-deploy Playbook. I created a new user for the Dimension-Server. When the playbook starts the Dimension Server I got the following Error in journalctl:

[index] The access token configured for Dimension belongs to a user which is also a user known to Dimension. This usually indicates that the access token is not a dedicated user account for Dimension. To prevent potential confusion to this user, Dimension will refuse to start until the access token given belongs to a dedicated user.
Error: Access token belongs to a real user. See logs for details. 

I have removed the configuration files and droped the dimension database. After starting the playbook, I got the same error.

**Comment by turt2live** [comment]
It means the user has a Dimension access token in the database for some reason. It should be a dedicated user account.

Please use the support room for support.

**Comment by cobordism** [comment]
same error for me.
I created a user just for this, but I also encounter the error. What is the way to make dimension forget this user / reset?
