### ISSUE TITLE
Dimension integration manager not receiving maintenance anymore

### ISSUE THREAD

**Issue by ToeiRei** [turt2live/matrix-dimension#515]
The repo states:

```
Please be aware that Dimension is no longer formally maintained. 
Bugs are not being looked at, and features are not being implemented. 
Support for the project is extremely limited as well - please check the issue tracker
before attempting to use Dimension.
```

Due to some outstanding bugs I would suggest dropping it and adding https://github.com/maunium/stickerpicker for managing stickers...

**Comment by sebix** [comment]
> Due to some outstanding bugs I would suggest dropping it

dropping it *where*?

**Comment by ToeiRei** [comment]
> dropping it where

This playbook

**Comment by ToeiRei** [comment]
Never mind. Wrong repo.
