### ISSUE TITLE
Add Jitsi widget

### ISSUE THREAD

**Issue by turt2live** [turt2live/matrix-dimension#87]
If possible, self-host. If using upstream (scalar), open a new ticket to add self-hosted option.

Related: https://github.com/turt2live/matrix-dimension/issues/38

**Comment by saket424** [comment]
Any plans to accelerate jitsi widget? It seems critical to conferencing in matrix/riot and it would be lovely to be able to self-host the jitsi widget. If I were more proficient, I would have submitted a pull request for this. Hopefully, someone is already working on this  matrix-dimension jitsi widget and will share it soon.

What I could glean so far is

https://scalar.vector.im/api/widgets/jitsi.html?confId=KyOjXOsRnnXCXWtekji1examplecom92wqhj7vjwv&isAudioConf=false&displayName=dq12&avatarUrl=&email=%40dq12%3Aa2.example.com

Here is what jitsi.html looks like
---------------------
<!doctype html>
<html id="jitsi-widget">
<head>
  <meta charset="utf-8">
  <title>Jitsi</title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="description" content="Matrix.org Jitsi Widget">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
</head>
<body>
  <div id="contentDiv">
  </div>
  <script src="https://jitsi.riot.im/libs/external_api.min.js"></script>
  <script type="text/javascript">
    var widgetName = 'jitsi';
    var scalarTokenMatch = document.location.search.match(/[?&](scalar_token=[^&]+)/);
    if (scalarTokenMatch) {
      document.cookie = scalarTokenMatch[1] + ";Path=/;" + (document.domain === "localhost" ? "" : "Secure;");
    }
    var script = document.createElement('script');
    script.type = "text/javascript";
    script.src = widgetName + ".bundle.js";
    var head = document.getElementsByTagName('head')[0];
    head.appendChild(script);
  </script>
</body>
</html>
--------------------------

And here is an extract from jitsi.bundle.js that implements the join jitsi conference on button click based on the various query parameters being entered.

        function t(e) {
            o(this, t);
            var n = i(this, (t.__proto__ || Object.getPrototypeOf(t)).call(this, e));
            return n.state = {
                showJoinButton: !0
            },
            n.queryParams = h.default.getQueryParameters(),
            n.config = {},
            !0 !== n.queryParams.isAudioConf && "true" !== n.queryParams.isAudioConf || (n.config.startVideoMuted = 0),
            n._joinButtonOnClick = n._joinButtonOnClick.bind(n),
            n._readyToClose = n._readyToClose.bind(n),
            n._setSize = n._setSize.bind(n),
            n
        }
        return a(t, e),
        s(t, [{
            key: "_readyToClose",
            value: function() {
                this.api.removeListener("readyToClose", this._readyToClose),
                this.api.dispose(),
                this.api = null,
                this.setState({
                    showJoinButton: !0
                })
            }
        }, {
            key: "_joinButtonOnClick",
            value: function() {
                this.api = new JitsiMeetExternalAPI(y.default.jitsi_domain,this.queryParams.confId,v.default.windowWidth(),v.default.windowHeight(),document.querySelector("#jitsiDiv"),this.config,{
                    SHOW_JITSI_WATERMARK: !1,
                    SHOW_WATERMARK_FOR_GUESTS: !1,
                    MAIN_TOOLBAR_BUTTONS: [],
                    VIDEO_LAYOUT_FIT: "height"
                }),
                this.queryParams.displayName && this.api.executeCommand("displayName", decodeURIComponent(this.queryParams.displayName)),
                this.queryParams.avatarUrl && this.api.executeCommand("avatarUrl", decodeURIComponent(this.queryParams.avatarUrl)),
                this.queryParams.email && this.api.executeCommand("email", decodeURIComponent(this.queryParams.email)),
                this.api.on("readyToClose", this._readyToClose),
                this.setState({
                    showJoinButton: !1
                }),
                this._setSize()
            }
        }, {
            key: "_setSize",
            value: function() {
                var e = v.default.windowWidth() + "px"
                  , t = v.default.windowHeight() + "px";
                (0,
                h.default)("body").css({
                    width: e,
                    height: t
                }),
                (0,
                h.default)('iframe[id^="jitsiConferenceFrame"]').css({
                    width: e,
                    height: t
                })
            }
        }, {
            key: "componentDidMount",
            value: function() {
                this._setSize()
            }
        }, {
            key: "componentWillUnmount",
            value: function() {
                this._readyToClose()
            }
        }, {
            key: "render",
            value: function() {
                return this.queryParams.confId ? l.default.createElement("div", {
                    id: "jitsiDiv"
                }, this.state.showJoinButton && l.default.createElement("div", {
                    id: "buttonContainer"
                }, l.default.createElement("h1", {
                    id: "title"
                }, "Jitsi Video Conference"), l.default.createElement("button", {
                    id: "joinButton",
                    type: "button",
                    onClick: this._joinButtonOnClick
                }, "Join Conference")), l.default.createElement(f.WindowResizeListener, {
                    onResize: this._setSize
                })) : l.default.createElement(WidgetError, {
                    error: "Conference ID not set"
                })
            }
        }]),
        t
    }(l.default.Component);
    p.default.render(l.default.createElement(b, null), document.getElementById("contentDiv"))
}

**Comment by turt2live** [comment]
Due to licencing (and morals), Dimension can't rip scalar's code as-is into the project and needs to be net-new. It can use it as inspiration, but shouldn't be used verbatim.

**Comment by t3chguy** [comment]
Plus it'd be unmaintainable

**Comment by turt2live** [comment]
This has been implemented! 🎉
